apiVersion: apps/v1
kind: Deployment
metadata:
        name: deployment-php-glpi
        labels:
                app: docker-php
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: docker-php
        template:
                metadata:
                        labels:
                                app: docker-php
                spec:
                        containers:
                                - name: docker-php
                                  image: gcr.io/projeto-test-249713/php-glpi
                                  ports:
                                          - containerPort: 80

                                                  
