apiVersion: v1
kind: Service
metadata:
  name: service-php
spec:
        selector:
                app: docker-php
        type: LoadBalancer
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
